--drop table if exists users;
--drop table if exists roles;
--drop table if exists user_roles;
create table users (id bigint generated by default as identity, name varchar(255) NOT NULL UNIQUE, password varchar(255) NOT NULL, primary key(id));
create table roles (id bigint generated by default as identity, name varchar(255) NOT NULL, primary key(id));
create table user_roles (id bigint generated by default as identity, user_id bigint NOT NULL, role_id bigint NOT NULL, primary key(id));

alter table user_roles add constraint users_constraint foreign key (user_id) references users(id);
alter table user_roles add constraint roles_constraint foreign key (role_id) references roles(id);
--ALTER TABLE USERS ADD CONSTRAINT USERNAME_CONSTRAINT UNIQUE(NAME);
